<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>IfcProbe</AssemblyName>
    <RootNamespace>IfcProbe</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xbim.Essentials" Version="6.0.*" />
  </ItemGroup>
</Project>
